/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BooksRouteImport } from './routes/books'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as BlogsCtgRouteImport } from './routes/blogs_.$ctg'
import { Route as BlogsCtgIdRouteImport } from './routes/blogs_.$ctg_.$id'

const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsCtgRoute = BlogsCtgRouteImport.update({
  id: '/blogs_/$ctg',
  path: '/blogs/$ctg',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsCtgIdRoute = BlogsCtgIdRouteImport.update({
  id: '/blogs_/$ctg_/$id',
  path: '/blogs/$ctg/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/blogs/$ctg': typeof BlogsCtgRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/blogs/$ctg/$id': typeof BlogsCtgIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/blogs/$ctg': typeof BlogsCtgRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/blogs/$ctg/$id': typeof BlogsCtgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/blogs_/$ctg': typeof BlogsCtgRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/blogs_/$ctg_/$id': typeof BlogsCtgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs'
    | '/books'
    | '/contact'
    | '/courses'
    | '/blogs/$ctg'
    | '/demo/tanstack-query'
    | '/blogs/$ctg/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs'
    | '/books'
    | '/contact'
    | '/courses'
    | '/blogs/$ctg'
    | '/demo/tanstack-query'
    | '/blogs/$ctg/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs'
    | '/books'
    | '/contact'
    | '/courses'
    | '/blogs_/$ctg'
    | '/demo/tanstack-query'
    | '/blogs_/$ctg_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRoute
  BooksRoute: typeof BooksRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  BlogsCtgRoute: typeof BlogsCtgRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  BlogsCtgIdRoute: typeof BlogsCtgIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs_/$ctg': {
      id: '/blogs_/$ctg'
      path: '/blogs/$ctg'
      fullPath: '/blogs/$ctg'
      preLoaderRoute: typeof BlogsCtgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs_/$ctg_/$id': {
      id: '/blogs_/$ctg_/$id'
      path: '/blogs/$ctg/$id'
      fullPath: '/blogs/$ctg/$id'
      preLoaderRoute: typeof BlogsCtgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRoute,
  BooksRoute: BooksRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  BlogsCtgRoute: BlogsCtgRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  BlogsCtgIdRoute: BlogsCtgIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
